feat: estrutura base das entidades Pessoa e Banco, para prosseguir no…
denisdev-cepedi/Cepedi.BancoCentral.Cadastro pull request #2
Opened 2024-04-24 19:49 UTC by Beatriz-ux

Precisei subir o inicio das entidades Pessoa e Banco, para concluir os endpoints de Registro de Transações.

2024-04-25 17:05 UTC, denisdev-cepedi requested changes

2024-04-25 17:05 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dados/Repositories/RegistroTransacaoBancoRepository.cs
> +        var id = registroTransacaoBanco.IdRegistro;
Qual a necessidade desse id?

2024-04-25 17:05 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dominio/Handlers/CriarRegistroTransacaoRequestHandler.cs
> +        if (request.Valor <= 0)
Isso poderia ficar no validation

2024-04-25 17:05 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dominio/Handlers/CriarRegistroTransacaoRequestHandler.cs
> +        {
Você não deveria lançar exceção para validação de regra de negócio. Deve retornar um erro com uma mensagem

2024-04-25 19:30 UTC, Beatriz-ux commented on src/Cepedi.BancoCentral.Cadastro.Dados/Repositories/RegistroTransacaoBancoRepository.cs
> +        var id = registroTransacaoBanco.IdRegistro;
Acabei esquecendo de remover.

2024-04-26 13:23 UTC, denisdev-cepedi approved these changes

2024-04-26 13:23 UTC, merged