Criando entidade banco
denisdev-cepedi/Cepedi.BancoCentral.Cadastro pull request #6
Opened 2024-05-07 14:23 UTC by BrendomGoncalves

2024-05-07 17:43 UTC, denisdev-cepedi requested changes

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Api/Controllers/BaseController.cs
> +﻿using Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Api/Controllers/BaseController.cs
> +        _ => BadRequest(FormatErrorMessage(Shareable.Enums.Cadastro.Generico))
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Api/Controllers/TipoRegistroController.cs
> +using Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Api/Controllers/UserController.cs
> +using Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Enums/Cadastro.cs
> +﻿using Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Enums/Cadastro.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Enums;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Enums/ETipoErro.cs
> +﻿namespace Cepedi.BancoCentral.Cadastro.Shareable.Enums;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Excecoes/ExcecaoAplicacao.cs
> +﻿namespace Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Excecoes/RequestInvalidaExcecao.cs
> +﻿namespace Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Excecoes/ResultadoErro.cs
> +﻿using Cepedi.BancoCentral.Cadastro.Shareable.Enums;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Excecoes/ResultadoErro.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Excecoes/SemResultadosExcecao.cs
> +﻿namespace Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/AtualizarBancoRequest.cs
> +using Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/AtualizarBancoRequest.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Requests;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/AtualizarTipoRegistroRequest.cs
> +﻿using Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/AtualizarTipoRegistroRequest.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Requests;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/CriarBancoRequest.cs
> +using Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/DeletarBancoRequest.cs
> +using Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/DeletarBancoRequest.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Requests;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/DeletarTipoRegistroRequest.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Requests;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/ObtemBancoRequest.cs
> +using Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/ObtemBancoRequest.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Requests;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/ObtemListaBancoRequest.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Requests;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/ObtemListaTipoRegistroRequest.cs
> +﻿using Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/ObtemTipoRegistroRequest.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Requests;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Requests/ObtemTipoRegistroRequest.cs
> +﻿using Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Responses/AtualizarBancoResponse.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Responses/AtualizarTipoRegistroResponse.cs
> +﻿namespace Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Responses/CriarBancoResponse.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Responses/CriarTipoRegistroResponse.cs
> +﻿namespace Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Responses/DeletarBancoResponse.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Responses/DeletarTipoRegistroResponse.cs
> +﻿namespace Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Responses/ObtemBancoResponse.cs
> +namespace Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Compartilhado/Responses/ObtemTipoRegistroResponse.cs
> +﻿namespace Cepedi.BancoCentral.Cadastro.Shareable.Responses;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dados/ApplicationDbContext.cs
> +namespace Cepedi.BancoCentral.Cadastro.Data;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dados/EntityTypeConfiguration/BancoEntityTypeConfiguration.cs
> +namespace Cepedi.BancoCentral.Cadastro.Data.EntityTypeConfiguration;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dados/EntityTypeConfiguration/TipoRegistroEntityTypeConfiguration.cs
> +namespace Cepedi.BancoCentral.Cadastro.Data.EntityTypeConfiguration;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dados/EntityTypeConfiguration/UsuarioEntityTypeConfiguration.cs
> +namespace Cepedi.BancoCentral.Cadastro.Data.EntityTypeConfiguration;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dados/Repositories/BancoRepository.cs
> +namespace Cepedi.BancoCentral.Cadastro.Data.Repositories;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dados/Repositories/TipoRegistroRepository.cs
> +namespace Cepedi.BancoCentral.Cadastro.Data.Repositories;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dados/Repositories/UsuarioRepository.cs
> +namespace Cepedi.BancoCentral.Cadastro.Data.Repositories
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Dominio/Handlers/DeletarTipoRegistroRequestHandler.cs
> +using Cepedi.BancoCentral.Cadastro.Shareable.Requests;
Porque você está mudando o namespace?

2024-05-07 17:43 UTC, denisdev-cepedi commented on tests/Cepedi.BancoCentral.Cadastro.Data.Tests/MemoryDatabase/UserRepositoryTests.cs
> +using Cepedi.BancoCentral.Cadastro.Data;
Porque você está mudando o namespace?

2024-05-07 18:27 UTC, BrendomGoncalves commented on src/Cepedi.BancoCentral.Cadastro.Api/Controllers/BaseController.cs
> +﻿using Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Eu uso o Rider, ele acusou erro nos namespace. Acho que devo ter colocado pra corrigir sem querer.

2024-05-08 19:10 UTC, denisdev-cepedi requested changes

2024-05-08 19:10 UTC, denisdev-cepedi commented on src/Cepedi.BancoCentral.Cadastro.Api/Controllers/BaseController.cs
> +﻿using Cepedi.BancoCentral.Cadastro.Shareable.Excecoes;
Ok, volte ao que era.

2024-05-09 19:15 UTC, closed without merging